Homework 2
================
Yuyi Lin
2026-10-04

``` r
library(tidyverse)
library(readxl)
```

# Problem 1

``` r
transit_df = 
  read_csv(
    "data/NYC_Transit.csv",
    col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")
  )|>
  janitor::clean_names()|>
  select(line, station_name, station_latitude, station_longitude, entry, vending, entrance_type, ada, starts_with("route")
  )|>
 mutate(
    entry =
      case_match(
        entry,
        "YES" ~ TRUE,
        "NO" ~ FALSE
      )
  )|>
  distinct(station_name, .keep_all=TRUE)
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
transit_df
```

    ## # A tibble: 356 × 19
    ##    line     station_name        station_latitude station_longitude entry vending
    ##    <chr>    <chr>                          <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue 25th St                         40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue 36th St                         40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue 45th St                         40.6             -74.0 TRUE  YES    
    ##  4 4 Avenue 53rd St                         40.6             -74.0 TRUE  YES    
    ##  5 4 Avenue 59th St                         40.6             -74.0 TRUE  YES    
    ##  6 4 Avenue 77th St                         40.6             -74.0 TRUE  YES    
    ##  7 4 Avenue 86th St                         40.6             -74.0 TRUE  YES    
    ##  8 4 Avenue 95th St                         40.6             -74.0 TRUE  YES    
    ##  9 4 Avenue 9th St                          40.7             -74.0 TRUE  YES    
    ## 10 4 Avenue Atlantic Av-Barcla…             40.7             -74.0 TRUE  YES    
    ## # ℹ 346 more rows
    ## # ℹ 13 more variables: entrance_type <chr>, ada <lgl>, route1 <chr>,
    ## #   route2 <chr>, route3 <chr>, route4 <chr>, route5 <chr>, route6 <chr>,
    ## #   route7 <chr>, route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>

``` r
  head(transit_df,20)
```

    ## # A tibble: 20 × 19
    ##    line            station_name station_latitude station_longitude entry vending
    ##    <chr>           <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue        25th St                  40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue        36th St                  40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue        45th St                  40.6             -74.0 TRUE  YES    
    ##  4 4 Avenue        53rd St                  40.6             -74.0 TRUE  YES    
    ##  5 4 Avenue        59th St                  40.6             -74.0 TRUE  YES    
    ##  6 4 Avenue        77th St                  40.6             -74.0 TRUE  YES    
    ##  7 4 Avenue        86th St                  40.6             -74.0 TRUE  YES    
    ##  8 4 Avenue        95th St                  40.6             -74.0 TRUE  YES    
    ##  9 4 Avenue        9th St                   40.7             -74.0 TRUE  YES    
    ## 10 4 Avenue        Atlantic Av…             40.7             -74.0 TRUE  YES    
    ## 11 4 Avenue        Bay Ridge Av             40.6             -74.0 TRUE  YES    
    ## 12 4 Avenue        DeKalb Av                40.7             -74.0 TRUE  YES    
    ## 13 4 Avenue        Pacific St               40.7             -74.0 TRUE  YES    
    ## 14 4 Avenue        Prospect Av              40.7             -74.0 TRUE  YES    
    ## 15 4 Avenue        Union St                 40.7             -74.0 TRUE  YES    
    ## 16 42nd St Shuttle Grand Centr…             40.8             -74.0 TRUE  YES    
    ## 17 42nd St Shuttle Times Square             40.8             -74.0 TRUE  YES    
    ## 18 6 Avenue        14th St                  40.7             -74.0 TRUE  YES    
    ## 19 6 Avenue        23rd St                  40.7             -74.0 TRUE  YES    
    ## 20 6 Avenue        2nd Av                   40.7             -74.0 TRUE  YES    
    ## # ℹ 13 more variables: entrance_type <chr>, ada <lgl>, route1 <chr>,
    ## #   route2 <chr>, route3 <chr>, route4 <chr>, route5 <chr>, route6 <chr>,
    ## #   route7 <chr>, route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>

``` r
  tail(transit_df,5)
```

    ## # A tibble: 5 × 19
    ##   line             station_name station_latitude station_longitude entry vending
    ##   <chr>            <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ## 1 White Plains Ro… Intervale Av             40.8             -73.9 TRUE  YES    
    ## 2 White Plains Ro… Jackson Av               40.8             -73.9 TRUE  YES    
    ## 3 White Plains Ro… Simpson St               40.8             -73.9 TRUE  YES    
    ## 4 White Plains Ro… Wakefield-2…             40.9             -73.9 TRUE  YES    
    ## 5 Flushing         34 St Hudso…             40.8             -74.0 TRUE  YES    
    ## # ℹ 13 more variables: entrance_type <chr>, ada <lgl>, route1 <chr>,
    ## #   route2 <chr>, route3 <chr>, route4 <chr>, route5 <chr>, route6 <chr>,
    ## #   route7 <chr>, route8 <chr>, route9 <chr>, route10 <chr>, route11 <chr>

This dataset includes several character and numerical variables
describing the MTA train station. There are 19 variables and 356
observations total. This means that after reducing to 1 station name per
row, we find that there are 356 unique stations total. The data is not
tidy, as route number and route name are not distinct variables.

``` r
transit_df|>
  filter(ada==TRUE)|>
  select(station_name, line)|>
  distinct()
```

    ## # A tibble: 57 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # ℹ 47 more rows

84 stations are ADA compliant.

``` r
transit_df|>
  filter(vending =="NO")|>
  pull(entry)|>
  mean(na.rm=TRUE)
```

    ## [1] 0.5555556

55.56% of station entrances/edits without vending allow entrance.

``` r
transit_tidy_df = 
  transit_df|>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name")

distinct_a = 
  transit_tidy_df |>
  filter(route_name=="A")|>
  distinct(station_name, line)

distinct_ada_a = 
  transit_tidy_df |>
  filter(route_name=="A", ada==TRUE)|>
  distinct(station_name, line)
```

There are 48 distinct stations that serve the A train. Of the stations
that serve the A, 10 are ADA compliant.

# Problem 2

``` r
trash_df = 
  read_excel("data/Trash_Wheel_2026.xlsx",
     na = c(""),
  sheet = "Mr. Trash Wheel",
  range = "A2:N743"
  )|>
  filter(!is.na(Dumpster))|>
  janitor::clean_names()|>
 mutate(
   year=as.numeric(year),
  plastic_bottles = as.numeric(plastic_bottles)
  )
  
professor_df = 
  readxl::read_excel("data/Trash_Wheel_2026.xlsx",
    na = c(""),
  sheet = "Professor Trash Wheel",
  range = "A2:M140"
  )|>
  filter(!is.na(Dumpster))|>
  janitor::clean_names()|>
 mutate(
   year=as.numeric(year),
  plastic_bottles = as.numeric(plastic_bottles)
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `plastic_bottles = as.numeric(plastic_bottles)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
gwynnda_df = 
  readxl::read_excel("data/Trash_Wheel_2026.xlsx",
    na = c(""),
  sheet = "Gwynnda the Good Wheel of the W",
  range = "A2:L395"
  )|>
  filter(!is.na(Dumpster))|>
  janitor::clean_names()|>
 mutate(
   year=as.numeric(year),
  plastic_bottles = as.numeric(plastic_bottles)
  )

merge_df = 
  bind_rows (trash_df, professor_df, gwynnda_df)|>
   mutate(
    sports_balls = as.integer(round(sports_balls))
  )
```

The new dataset, which ranges from 2014 to 2026, has 1269 observations
and 14 variables, where the average number of sports balls collected was
15.04. Key variables include which dumpster collected the trash, the
time (month, year, and date) trash was collected, the weight and volume
of trash, the number of different trash types (ex. plastic, cigarettes,
sports balls), and the amount of electricity generated after burning.

For available data, Professor Trash Wheel collected a total of 294.96
tons of trash.

``` r
gwynnda_cig = 
  gwynnda_df |>
  filter (year==2022, month == "June") |>
  pull(cigarette_butts)|>
  sum(na.rm=TRUE)
```

Gwynnda collected a total of 1.812^{4} cigarette butts in June 2022.

# Problem 3

``` r
baseline_df = 
  read_csv("data/data_mci/mci_baseline.csv",
 skip = 1,
 na = c("$",".")
  )|>
  janitor::clean_names()|>
  mutate(
    sex = as.factor(sex),
    apoe4 = as.factor(apoe4)
  )|>
  filter(
    age_at_onset > current_age | is.na(age_at_onset)
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Originally, I had used the unzip and exdir function to put the new files
in my data folder. After OH, Gustavo suggested I just clicked manually
on the zip file, which immediately opened up the data_mci folder within
my data folder. After filtering participants (original file had 483
observations), there were 479 participant ID rows and 6 variables total,
which includes participant characteristics such as age at baseline, sex,
carrier status, sex, and age at onset of MCI, if applicable.

Of the 479 participants recruited 93 developed MCI. The average baseline
age is 65.03, and NA of women in the study were APOE4 carriers.

``` r
amyloid_df = 
  read_csv("data/data_mci/mci_amyloid.csv",
    skip = 1,
    na = c("NA","","Na"))|>
  janitor::clean_names()
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
merge_mci_df = 
  inner_join (baseline_df, amyloid_df, by = c("id"="study_id")
  )

write_csv(
  merge_mci_df, ("data/merge_mci.csv")
  )
```

Dataset followed similar tidying steps as baseline_df where first column
was skipped, missing codes were specified and removed, and text grammar
was corrected. Similar to baseline_df, rows (total=487 observations)
were participant ID. However, columns contained the different times
(total=6 variables; 2, 4, 6, and 8 years) that have elapsed since the
study baseline to the visit when biomarker amyloid was measured.

8 participants appeared in only the baseline dataset, and 16
participants appeared in only the amyloid dataset. The combined dataset
now has 471 observations and 11 variables total. This makes sense
because there were 6 variables in each dataset (total=12 variables) with
1 common variable (ID), and 479 - 8 = 471 common rows from the baseline
dataset while 487 - 16 = 471 common rows from the amyloid dataset.
